apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-processor.fullname" . }}-secret
  labels:
    {{- include "telemetry-processor.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.dbPassword | quote }}
