apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "telemetry-processor.fullname" . }}
  labels:
    {{- include "telemetry-processor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "telemetry-processor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
