apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-processor.fullname" . }}
  labels:
    {{- include "telemetry-processor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "telemetry-processor.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
