apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestion-service.fullname" . }}-config
  labels:
    {{- include "ingestion-service.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.kafkaBootstrapServers | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.env.kafkaSecurityProtocol | quote }}
  KAFKA_USERNAME: {{ .Values.env.kafkaUsername | quote }}
  TELEMETRY_TOPIC: {{ .Values.env.telemetryTopic | quote }}
  INGESTION_PORT: {{ .Values.env.ingestionPort | quote }}
