# Применяется на ArgoCD, установленной в кластере Yandex Cloud:
#   kubectl apply -f argocd/yandex/query-service.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: query-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Andrey834/telemetry-system.git
    targetRevision: main
    path: helm/query-service
    helm:
      valuesObject:
        image:
          repository: cr.yandex/crp9isuggbupe94f02pg/query-service
        imagePullSecrets: []
        env:
          redisHost: "rc1d-itc1ni5lemrlldil.mdb.yandexcloud.net"
        credentialsSecretName: query-service-credentials

  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
