# Применяется на ArgoCD, установленной в кластере Yandex Cloud:
#   kubectl apply -f argocd/yandex/telemetry-processor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telemetry-processor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Andrey834/telemetry-system.git
    targetRevision: main
    path: helm/telemetry-processor
    helm:
      valuesObject:
        image:
          repository: cr.yandex/crp9isuggbupe94f02pg/telemetry-processor
        imagePullSecrets: []
        env:
          kafkaBootstrapServers: "bootstrap.c9qg0ilp22vs9q3tpioq.mdb.yandexcloud.net:9091"
          kafkaSecurityProtocol: "SASL_SSL"
          kafkaUsername: "telemetry"
          redisHost: "rc1d-itc1ni5lemrlldil.mdb.yandexcloud.net"
          dbHost: "rc1d-g51d7k1sb633pgdn.mdb.yandexcloud.net"
          dbPort: "6432"
          dbSslMode: "require"
          dbSslEnabled: "true"
        credentialsSecretName: telemetry-processor-credentials

  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
