apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-service.fullname" . }}-config
  labels:
    {{- include "query-service.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.env.redisPort | quote }}
  QUERY_PORT: {{ .Values.env.queryPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.env.corsAllowedOrigins | quote }}
  DB_REPLICA_HOST: {{ .Values.env.dbReplicaHost | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_SSL_MODE: {{ .Values.env.dbSslMode | quote }}
